### ISSUE TITLE
请问支持后台上传吗？

### ISSUE THREAD

**Issue by ancoo** [huhuanming/qiniu_upload#10]

**Comment by ancoo** [comment]
我测试了下 不支持后台上传
请问有这方面的开发计划吗

**Comment by huhuanming** [comment]
0  w  0 可以啊，可以加入的。。我待会儿加到 TODO 里面吧

**Comment by huhuanming** [comment]
@ancoo 你好。。我研究了下 Background Transfer Service 的文档，发现其实并不需要修改这个的源码，如果你还是不清楚如何操作的话，周末的时候，我可以在这个 repo 里面提供一份 example。

**Comment by huhuanming** [comment]
如果没有其他疑问的话，这个 issue 就关闭了噢？

**Comment by ancoo** [comment]
@huhuanming 谢谢回复 那我求一份example 么么哒

**Comment by huhuanming** [comment]
周末的时候吧。。。。0 -  0工作日太忙。。这个 issue 先留着

**Comment by bytegh** [comment]
还是需要修改的 目前你那边用的dataTaskWithRequest来做的，需要用其他支持background upload的接口

**Comment by huhuanming** [comment]
了解了。。

**Comment by huhuanming** [comment]
0  -  0当时粗略看了下。。以为都一样

**Comment by huhuanming** [comment]
多谢提醒

**Comment by bytegh** [comment]
😁

**Comment by huhuanming** [comment]
延期两天。。。0  - 0本周太忙，下周会解决的

**Comment by huhuanming** [comment]
着手搞咯

**Comment by huhuanming** [comment]
这个问题还不是那么好解决，是这样的
1. Background Transfer Service  只支持 NSURLSessionUploadTask 和 NSURLSessionDownloadTask
2. NSURLSessionUploadTask 中只有 uploadTaskWithRequest:(NSURLRequest *)request fromFile:(NSURL *)fileURL 能够执行 Background Transfer Service，formdata 会直接报错
3. 我在这里实现的是表单直传，表单直传的话，fromFile 这个 API 是不支持直传的。

所以我的解决方案是
1. 先支持分片上传，分片上传的 Content-Type 是  application/octet-stream，就能够支持在 uploadTaskWithRequest 里面跑
2. 支持分片后 NSURLSessionUploadTask 里面的 fromFile 终于支持上传了
3. 但也只能  fromFile 能后台
4. 如果分片的话，还得看 file 大小再后台上传

总之就是这么复杂0  - 0有啥更好的解决方案可以指教一下吗

**Comment by huhuanming** [comment]
0  -  0  那我得先把分片上传搞了。。。

-  -也有其他后台方案，比如像 B 站靠放歌什么的方案的话，我觉得我这边就不会默认集成这种方案了。
