### ISSUE TITLE
请问为什么uploadOneFileFailed在定义的时候error类型与使用时不一样？

### ISSUE THREAD

**Issue by Junetea** [huhuanming/qiniu_upload#11]
uploadOneFileFailed在定义的时候，参数error为NSDictionary类型，但是在QiniuUploader中使用的时候却是NSError类型

**Comment by huhuanming** [comment]
0  -  0 失误了诶，没注意到这个问题，今晚会统一成 NSError，然后重新发布

谢谢你的反馈 0 w  0

**Comment by huhuanming** [comment]
突然发现。。要更新 Xcode 了。。。

![image](https://cloud.githubusercontent.com/assets/5743863/18497269/55407e8e-7a5f-11e6-9f16-330f1cbc1bc3.png)

**Comment by kuco0614** [comment]
Po主你这么萌真的好吗😂

**Comment by huhuanming** [comment]
😂 悲伤。。白苹果了。。。

**Comment by kuco0614** [comment]
黑人问号.jpg 更新iOS 10白苹果了么？

**Comment by huhuanming** [comment]
0  - 0 恢复到 9.3 然后再升级到 iOS 10 就好了。。果然不能 OTA。。。

**Comment by huhuanming** [comment]
我修复这个问题了。。等会儿发一个版本

**Comment by huhuanming** [comment]
issue 先关闭了噢
