### ISSUE TITLE
do not support AFNetworkingSession

### ISSUE THREAD

**Issue by beforeold** [huhuanming/qiniu_upload#12]
hope you can update support AFNetwoking 2.0+

**Comment by huhuanming** [comment]
Hey, friends, I removed AFNetWorking support just now.

But, the great idea is you could use qiniu_upload without any depency.

Not cool ? Or you don't know how to use it without  AFNetwoking ?

Whatever, thanks for your advise.

![explaining my thoughts in a single sentence good job _3514d31ebe3c746bfb0da884e5c4a679-1](https://cloud.githubusercontent.com/assets/5743863/18579748/1bdc6e74-7c2a-11e6-97b7-0ced745d46f5.jpg)

**Comment by huhuanming** [comment]
Do you have any question again? 😁


---
if you have other question, you could open another issue.

good luck~~

**Comment by beforeold** [comment]
👍  Got it. You did a great jod. I realized you finish this all by yourself, not based on qiniu offical objc-sdk. Cool and fantastic job to solve multi-file upload task.

**Comment by huhuanming** [comment]
Thanks, friends. 😁

I want to make a universal uploader supporting all backends on iOS and  Android.

But the first step is Qiniu, and so much things need do do.

if you interested in it, you could open a pull request for this repo.

**Comment by beforeold** [comment]
😄 that's too difficult for me~

**Comment by huhuanming** [comment]
Don't overthink it, just have fun and play.
