### ISSUE TITLE
swift support

### ISSUE THREAD

**Issue by hyichao** [huhuanming/qiniu_upload#13]
亲测可用bridge方式使用到swift工程。
已stared。

**Comment by huhuanming** [comment]
谢谢支持。。0 w  0 虽然我更想提供原生的  Swift 方案。。 抽时间搞啦

**Comment by hyichao** [comment]
原生swift的话我也有点兴趣，感觉github上对七牛的支持不是很多，七牛自己的sdk写的也怪怪的。。不过要抽空先读完你这个oc库再看我能不能参与哈。。

**Comment by huhuanming** [comment]
0  w  0 赞。。其实我最终还是想实现一个支持所有上传终端的一个方案，比如  AWS，又拍云，七牛或者自己的方案。

如果有意的话，我们可以一起开个新的 repo 来解决下这个问题。

**Comment by huhuanming** [comment]
毕竟只是解决七牛的话意义不大，对于特定的服务商应该是类似 plugin 的方式去集成。
