### ISSUE TITLE
ios 

### ISSUE THREAD

**Issue by luo-h** [huhuanming/qiniu_upload#14]
你好，我cocoaPods下载最新的库，但是用不了，有些方法被弃用了，有些block也不对，[uploader startUploadWithAccessToken:qiniuToken];也用不了，请问你能更新下文档吗，谢谢，或者能加一下你的联系方式呢

**Comment by huhuanming** [comment]
明明可以的诶。。我都运行过。。

文档也更新过。

可以加微信 huhuanming，但是估计要到下班后才能回，不好意思。
