### ISSUE TITLE
上传时能加参数吗??

### ISSUE THREAD

**Issue by smallevil** [huhuanming/qiniu_upload#15]
上传时能加入一些自定义参数吗?
七牛是可以的,分为自定义和魔法.
魔法可以直接在服务器产生token时加进去.
但自定义参数好像只能上传时加吧.
而且有些参数是和客户端相关的.
我找了半天,没找到SDK里应该怎么加进去.
这样用回调时,七牛就可以直接把这些参数给服务器端了.会方便很多.
如果已经有的话,麻烦说一下怎么调用.
谢谢

**Comment by huhuanming** [comment]
1. 好哒。。token 的话可以从服务端获取添加，没什么问题
2. 本地的自定义参数的话，是希望支持七牛的全部自定义参数吗？

**Comment by huhuanming** [comment]
凌晨提问的啊？

**Comment by huhuanming** [comment]
还在吗。。。-  -

**Comment by smallevil** [comment]
七牛的自定义参数是自已随便写的.
想写什么都行.你可以看一下,是以"x:"开头的.
魔法参数是可以在生成token时加进去的,这个只要在服务器端搞定就OK了.
其实自定义参数,只要有一个字典能上传就行了.

**Comment by smallevil** [comment]
另外,我在今天在做测试.
发现一个有点奇怪的问题.
我上传图片成功了.
但是setUploadOneFileFailed这个给我返回出错了.
因为我的token产生时是有写回调的.
我看了一下,服务器端是有回调的,而且,七牛上也有我上传的文件.
不知道啥原因,会在这个函数返回错误...

**Comment by smallevil** [comment]
我觉得你可以扩展一下这个接口
- (id)initWithFileData:(NSData *)theData withKey:(NSString*)theKey

变成

- (id)initWithFileData:(NSData *)theData withKey:(NSString*)theKey ext:(NSDictionary *)ext

这样加入文件时,就可以直接把想要的自定义信息加进去,
你在上传时,可以上传到七牛,
因为七牛默认,上传的自定义信息都是会同步给回调接口的.
这样就可以把客户端的一些信息,与上传的照片绑定在一起了.

**Comment by huhuanming** [comment]
好哒。。。晚上搞搞。。0  m  0  传进去的自定义信息有哪些呢

天哪。。凌晨 5 点回复的吗。。

**Comment by smallevil** [comment]
所谓自定义就是,我想传啥都行.

因为是APP,而且是直接传给七牛的.
所以,总要知道是哪个用户传的吧.

我现在的流程是:
用户上传图片时,自定义参数里加用户ID传给七牛,
传成功了,七牛直接callback我服务器,然后我就可以直接入库了.这时有用户ID,有图片KEY,入库没问题,
而且,如果想做的细了,如果用户中途退出,以后也可以直接选择这些已上传的直接发.最差,也能知道,有哪些用户不断的传图片占用资源,但总是中途退出不能完成发贴了.
等都上传完了,APP这边把文字/KEY都POST到服务器,这时贴子再与图片关联就OK了.

其实如果做的细一点,七牛自定义参数里,除了用户ID之外,还可以再加一个随机数,这个随机数代表了,这几张图片是同一个贴子里的,这时用户再POST文章时,都不用上传KEY值了,直接上传这个随机数就能和图片关联起来了.

所以,只要能加自定义参数,那灵活度就高呀高呀高起来了.
呵呵

**Comment by huhuanming** [comment]
了解了。0  w 0空了我处理下哈。。大约本周内可以吗

**Comment by smallevil** [comment]
好的.多谢.
能尽快最好.
刚好写到上传,
你要是快,我也能赶点工.
哈哈.

**Comment by smallevil** [comment]
忘了,提醒你一下.
你版本提示写错了.
已经是2.0.2了.
但是pod里没改,所以,还是在提示呀提示.

**Comment by huhuanming** [comment]
好哒。。。i an sorry。。。

**Comment by smallevil** [comment]
哥们,怎么样了?
啥时间能发布?

**Comment by Sunny-leave** [comment]
- (void)putPHAsset:(PHAsset *)asset
               key:(NSString *)key
             token:(NSString *)token
          complete:(QNUpCompletionHandler)completionHandler
            option:(QNUploadOption *)option
不使用上传图片的那个方式 、用这一个方法 可以设置图片的大小或者说可以提交一个文件小一些的图片上传吗。因为这个方法上传、速度上有问题

**Comment by huhuanming** [comment]
十分抱歉。。0 -  0 你的期望是上传前压缩一下吗？
