### ISSUE TITLE
Token时效的问题

### ISSUE THREAD

**Issue by xingchenAtGithub** [huhuanming/qiniu_upload#17]
我有两个scope，scope1和scope2，两个scope的访问路径是不一样的。 第一次，我上传到scope1，然后我上传到scope2,这个过程中，scope1中的图片上传、读取正常。 但是我上传到scope2的图片上传失败，他实际上是上传到scope1中了
我想着,TOKEN能不能根据不同的scope生成对应Token，然后图片可以正确的上传到正确的scope，

**Comment by huhuanming** [comment]
这个确实是我没有考虑进去的问题。。可以初始化两个 uploader

**Comment by hydyy** [comment]
我这也有类似需求， token可否针对file，每个file放自己的token

**Comment by huhuanming** [comment]
好哒。0 - 0这周内我搞搞。。没搞出来。。发红包。。

**Comment by hydyy** [comment]
先拉个微信群，这叫背水一战！哈哈

**Comment by huhuanming** [comment]
0 -  0 不拉群不结盟。。没更新这周楼下放码就是

**Comment by hydyy** [comment]
🐂B

**Comment by huhuanming** [comment]
XD

**Comment by huhuanming** [comment]
没来得及更新。。。- - 留下微信发红包了只能 @hydyy

**Comment by hydyy** [comment]
哈哈 加个微信交个朋友哇， 红包就算了哇！ hzhydyy

**Comment by huhuanming** [comment]
https://github.com/huhuanming/qiniu_upload/tree/token_in_file

专属分支
