### ISSUE TITLE
楼主还会继续做这个开源吗？

### ISSUE THREAD

**Issue by hydyy** [huhuanming/qiniu_upload#18]
在犹豫要不要用，看到三个月没更新了

**Comment by huhuanming** [comment]
0  - 0额。。。可以先用用。。有问题最近有时间处理了。。

**Comment by hydyy** [comment]
@huhuanming 其实我想要分片跟后台。。。

**Comment by huhuanming** [comment]
分片的话。。-  -开了个新的 repo 在做。。中间因为玩别的东西所以停了。。
后台的话。原生 API 不支持。。你只能用写奇技淫巧来实现。。
这个的话就我个人而言的话是不推荐的

**Comment by hydyy** [comment]
好的，其实现在也满足大部分需求了。 期待更新

**Comment by huhuanming** [comment]
谢谢

**Comment by huhuanming** [comment]
如果没有其他疑问，我就 close 了噢。。0 -  0希望能在这个月完成新的 repo。。。一个支持分片的且可以随意切换 又拍云，七牛，s3 的通用上传控件
