### ISSUE TITLE
七牛地址已经变了

### ISSUE THREAD

**Issue by taidypanda** [huhuanming/qiniu_upload#19]
之前是*.qbox.me
现在是up-z2.qiniu.com

**Comment by huhuanming** [comment]
旧地址还能使用吗？

**Comment by github4dogg** [comment]
貌似不能用了啊
error: Error Domain=https://up.qbox.me Code=400 "{"error":"incorrect region, please use up-z2.qiniu.com"}" UserInfo={NSLocalizedDescription={"error":"incorrect region, please use up-z2.qiniu.com"}}

**Comment by huhuanming** [comment]
那我修改下哈。。。

**Comment by huhuanming** [comment]
马上改改。。。0 -  0居然地址都变了

**Comment by github4dogg** [comment]
只需要这样改一下就好了 

#define kQiniuUploadURL @"http://up-z2.qiniu.com"

**Comment by huhuanming** [comment]
但是我觉得 https 链接更好
https://upload.qbox.me

**Comment by huhuanming** [comment]
你觉得呢

**Comment by huhuanming** [comment]
🎉  Congrats

 🚀  QiniuUpload (2.0.3) successfully published
 📅  July 24th, 02:29
 🌎  https://cocoapods.org/pods/QiniuUpload
 👍  Tell your friends!
