### ISSUE TITLE
The progress delegate doesn't work

### ISSUE THREAD

**Issue by bagusflyer** [huhuanming/qiniu_upload#2]
My code: (in swift)

        let qToken = QiniuToken(scope: "abc", secretKey: "-mykey", accesskey: "myak")
        
        let data = NSData(contentsOfFile: NSBundle.mainBundle().resourcePath! + "/myfile.mp3")
        let file = QiniuFile(fileData: data)
        
        let uploader = QiniuUploader(token: qToken)
        uploader.addFile(file)
        uploader.delegate = self
        uploader.startUpload()

Only uploadAllFilesComplete being called. Any suggestion? Thanks.

**Comment by huhuanming** [comment]
I' m sorry that I only test it for image and text file.
I will work on it and reply to you as soon as possible, don't worry.

**Comment by bagusflyer** [comment]
Thanks. You did great job. My other question is how to get the url for the file just uploaded? Thanks

**Comment by huhuanming** [comment]
I test it for audio and video and  it can call all method now.
but I make a mistake for minetype and will solve it at once.

I can't understood  what you question for url?
If you upload success you will get data like this in  OneFileSucceeded method

QiniuUploadDemo[25550:6489870] index:2 ret:{
    hash = "loDyXEyyLF1T0Ocgo-X7AoA4mG3O";
    key = "loDyXEyyLF1T0Ocgo-X7AoA4mG3O";
}

finally 。。好累啊。。是中国人么。。( ͒•ㅈ• ͒)  你还有啥需求。我马上改代码改了就上传 Github 和 pod。。最新版我已经把 delegate 全部移除了 换成了 block了。。android的要么。。我一套都齐全的 还有angularjs的。。。

**Comment by huhuanming** [comment]
if you get key, you can  it like this:
http://7sbqrd.com2.z0.glb.clouddn.com/loDyXEyyLF1T0Ocgo-X7AoA4mG3O

好累啊。。=  =憋英文。。要内伤了。。

**Comment by bagusflyer** [comment]
哈哈，不好意思，没注意你是用中文写的。谢谢了，我看看。

**Comment by huhuanming** [comment]
=  皿 = 已经修正了上传音频和视频了。。马上上传哈。。我再测试下。。我这里已经ok了

**Comment by huhuanming** [comment]
http://7sbqrd.com2.z0.glb.clouddn.com/loDyXEyyLF1T0Ocgo-X7AoA4mG3O

**Comment by bagusflyer** [comment]
很好啊，谢谢。我刚刚开始看七牛。

**Comment by zhenghongchuan** [comment]
记得打个star哦~

发自我的 iPhone

**Comment by bagusflyer** [comment]
你新版在哪里？我想请教一下，上传完后，程序怎样获得刚上传的url呢？

**Comment by zhenghongchuan** [comment]
回调里有ret

发自我的 iPhone

**Comment by huhuanming** [comment]
新版正在上传。。=  皿  =稍微等一下下哈。。网络不太好。。容我挂个vpn 好了喊你

**Comment by bagusflyer** [comment]
多谢。你在哪个城市？

**Comment by huhuanming** [comment]
成都。
新版源码已经更新。。等下我去上传 pod。。还有什么问题请继续留言哈

**Comment by bagusflyer** [comment]
不要紧，我等你pod。以后多联系，谢谢了。

**Comment by huhuanming** [comment]
![image](https://cloud.githubusercontent.com/assets/5743863/7333926/121e9eec-ebb3-11e4-9ca1-73a4307c17e5.png)

1.0.1 版 pod 已上传。。自己注意更新吧。。demo github上面也可以看。。
 =  皿 =有问题 我继续更新
