### ISSUE TITLE
README.md文件#号的问题

### ISSUE THREAD

**Issue by github4dogg** [huhuanming/qiniu_upload#22]
下面这些标题都没有被识别出来,其实#后面需要加个空格,例如:

```
###如何开始 -> ### 如何开始
```

###如何开始

####从 CocoaPods 安装

#####Podfile pod "QiniuUpload"

####手动安装

复制Classes目录下的类到工程项目中就行了。

####开始编码

###QiniuToken

**Comment by github4dogg** [comment]
### 如何开始

**Comment by huhuanming** [comment]
太久没维护了。。
GitHub 更换了一次 markdown 解析。。

**Comment by huhuanming** [comment]
已经 fix 了
