### ISSUE TITLE
bad token 

### ISSUE THREAD

**Issue by liushuangddu** [huhuanming/qiniu_upload#23]
直接集成了你的 SDK, 但是一直报错:
(0, Optional(Error Domain=https://upload.qbox.me Code=401 "{"error":"bad token"}" UserInfo={NSLocalizedDescription={"error":"bad token"}}))
自我以为 AK 和 SK 这些都没有问题啊,能有什么问题!!!,但是还是报错,阿里云也是这样的问题,所以转战七牛,都是 token 出问题,我是直接用你的单利生成的,看不出来有什么问题,醉了...

**Comment by huhuanming** [comment]
别急

**Comment by liushuangddu** [comment]
????????,能给点建议吗,在线等

**Comment by huhuanming** [comment]
这个是七牛抛出的异常。
你用的模式是后端计算 token 还是在 iOS 端计算呢？

**Comment by liushuangddu** [comment]
iOS

**Comment by huhuanming** [comment]
检查一下 ak 和 sk 填写错没。。复制正确没，填写反没呢。。

**Comment by liushuangddu** [comment]
自己签名

**Comment by huhuanming** [comment]
我试试我的哈

**Comment by liushuangddu** [comment]
并没有

**Comment by huhuanming** [comment]
我试试我的先。。

**Comment by huhuanming** [comment]
我的 key 没问题。。
你先试试我的吧。。。
[QiniuToken registerWithScope:@"temp" SecretKey:@"_VJe8KatGauU08j_vOTqcSj2xuTR4SMcbAaKVpTN" Accesskey:@"2rc8_GcKfMEGvnEKqlSL0dzeaQbBM9sedGFiQ_6J"];

大约一小时后我会停用屌

**Comment by liushuangddu** [comment]
好的,我试试

**Comment by liushuangddu** [comment]
你的有返回,

**Comment by liushuangddu** [comment]
麻烦你看看服务器上有图片吗

**Comment by huhuanming** [comment]
那你要检查下你的 scope， sk， ak 填错了没。
图片名叫什么

**Comment by liushuangddu** [comment]
我不知道图片名叫什么呢
只返回了一串这个:
index:0key:FuteDWQ0NfdZ2a7HxDpeeMwUyaYG

**Comment by huhuanming** [comment]
http://7xqlzr.dl1.z0.glb.clouddn.com/FgPttIDTsWmvft0yuL9P3XaPtdNf

**Comment by huhuanming** [comment]
你检查下你的 Scope SK AK 呢。。说明代码是没问题的

**Comment by liushuangddu** [comment]
好的,那就应该是我的 key 出了问题.谢谢啦

**Comment by huhuanming** [comment]
不客气。。有问题可以继续在下面留言。。大约一天后关闭 issue

**Comment by liushuangddu** [comment]
OK 了,我换了一个 key, 这个 key 是去年的了0.0

**Comment by huhuanming** [comment]
0   。0 其实不推荐客户端上直接填。。

**Comment by liushuangddu** [comment]
懒的搞了# 

> ****

**Comment by huhuanming** [comment]
😂

**Comment by zhenghongchuan** [comment]
后端返多好啊...省时省力...

**Comment by huhuanming** [comment]
😳

**Comment by liushuangddu** [comment]
我们没有后端啊,,,,,,,,不想写了,,,,,,,,,,,,,,,,,啊啊啊啊啊啊啊啊
