### ISSUE TITLE
上传的图片没有后缀名???

### ISSUE THREAD

**Issue by liushuangddu** [huhuanming/qiniu_upload#24]
上传的图片没有后缀,浏览器可以解析,但是模拟器不行,我在上传的时候加了后缀:
let name = String.init(format: "/%@.jpeg", String.stringWithUUID())
            let imagePath = UIApplication.shared.documentsPath.appending(name)
            
            if let data = UIImageJPEGRepresentation(image, 1.0)

**Comment by huhuanming** [comment]
其实没后缀没影响的。。。
无论是浏览器还是图片控件都会根据 http 头或者 decode 来识别的。。
