### ISSUE TITLE
更新：支持多文件并发

### ISSUE THREAD

**Issue by huhuanming** [huhuanming/qiniu_upload#25]
将在本周内支持多文件并发，但这次更新之后将会移除一些旧的 API，
然后本项目就只维护修复 bug，不再更新新的功能了。

打算转向纯 Swift，无第三方依赖的，更模块化，支持更多服务，支持更多上传场景的 UploadKit 的开发，谢谢大家。

**Comment by zhenghongchuan** [comment]
Swift一起写也，我最近写了几个swift的项目

**Comment by zhenghongchuan** [comment]
妥，不过面向协议编程我觉得有的时候有点脱了裤子放屁的感觉

**Comment by huhuanming** [comment]
因为需要有更多的使用场景及更强的普适性。

Swift 中绝大多数定义协议的命名方式是以 able 或者 ible 结尾，为每个协议定义它的职责范围。

以后不会有 QiniuFile 这样的类，只会有 UploadFile 的 Protocol，
那么 UploadKit 就可以有更强的拓展性，只要继承了该协议，无论它的实现是什么样的，满足响应的接口即可。
这很 Java。

**Comment by zhenghongchuan** [comment]
牛批牛批，你到时候给个范例我看一哈

**Comment by huhuanming** [comment]
0 -   0 好。。

**Comment by zhenghongchuan** [comment]
结婚提前点给我说哈，我好存钱

**Comment by huhuanming** [comment]
😳。。还有两三年。。。

**Comment by zhenghongchuan** [comment]
说不准，擦枪走火，被迫结婚

**Comment by huhuanming** [comment]
![image](https://user-images.githubusercontent.com/5743863/29373851-147d01ec-82e2-11e7-9667-4f0a921fc64b.png)

**Comment by huhuanming** [comment]
@zhenghongchuan 

https://medium.com/@abhimuralidharan/all-about-protocols-in-swift-11a72d6ea354

可以先看看这个

**Comment by zhenghongchuan** [comment]
收到
