### ISSUE TITLE
"file is not specified in multipart"总是出现这个错误

### ISSUE THREAD

**Issue by smallevil** [huhuanming/qiniu_upload#26]
上传时总是会出现这个错误.
是哪设置不对?

我用的还是2.X的版本,暂时没有更新到最新的.
经常出现,不知道是哪的问题?

**Comment by huhuanming** [comment]
0   -   0  

可以尝试升级到新版本看看吗？

**Comment by smallevil** [comment]
一直没升也是因为改动有点大.
我在原来的基础上加了一些东西.
:(

你没遇到过吗?要是知道哪的问题,我直接改一下也行.

**Comment by huhuanming** [comment]
没事没事。。你说下具体版本嘛。。
然后能给一下你有问题的文件。。我测看看

**Comment by smallevil** [comment]
代码里写的是
versionName:2.0.0
version:10

**Comment by huhuanming** [comment]
是上传什么文件的时候报错呢

**Comment by huhuanming** [comment]
你是有 fork 我之前的版本吗？
那我可以直接上的 repo 查看吗？

**Comment by smallevil** [comment]
纯图片上传.
应该是2.0.0时我直接下载的ZIP然后放到我工程里的

**Comment by huhuanming** [comment]
我对比了下组装 http body 的代码。。好像没什么改动。

那改一下这个有用吗？
```
#define kQiniuUploadURL @"https://upload.qbox.me"
```

**Comment by smallevil** [comment]
代码里用的就是这个上传域名的.

**Comment by huhuanming** [comment]
这个问题出在。。上传的数据体里面没有 file

![image](https://user-images.githubusercontent.com/5743863/29742853-351fa88a-8ab9-11e7-81dc-753a10061a15.png)

检查一下 file 字段写入没有，可以在这里加一下断点吗？

**Comment by smallevil** [comment]
意思是没读到图片??

怪了.我是用一个相册选择,然后一个个加到upload里的.
理论上应该没事吧?

这个有没有什么办法判断然后去掉呢?

**Comment by huhuanming** [comment]
可以加一下断点，先看看。。只是我的一个推测
😳

**Comment by smallevil** [comment]
用户的环境太复杂了.
我自己怎么上传都没出过问题.
上线后,用户各种反馈说发不了.

**Comment by huhuanming** [comment]
用户的系统版本呢？

**Comment by smallevil** [comment]
都是最新的IOS版本的,
而且,我的app本身就限制最少8.0以上系统.

**Comment by smallevil** [comment]
而且,用户也不是每次必现的.
就是突然会出现一次.很奇怪的问题.
同样几张照片上传,有时会遇到,有时遇不到

**Comment by huhuanming** [comment]
感觉像是 10 下面会出现的问题，因为 10 下面。。照片不是能立即获取到的。。
因为默认相册是存在 iCloud 里面的。。

**Comment by huhuanming** [comment]
你可以尝试一下。。在自己的手机上测试。。
然后选一张本地不存在。。但是在 iCloud 云相册里面存在的照片吗

**Comment by smallevil** [comment]
我擦,把这个事给忘了.
那还真有可能.
那这个要怎么处理??
但按理来说,用图片选择工具能选中,应该就能读到的吧?
这个原理还真不是特别清楚了.

**Comment by huhuanming** [comment]
这个我就没有适配了，可能需要你自己处理下了，
处理方式也比较简单，就是不用 `AssetsLibrary`， 用 `PhotoKit`。

`PhotoKit` 本身是个异步的库，获取到图片后，会产生一个回调，回调里面可以直接拿到 `UIImage`，转成 `NSData` 去上传就行。（可能内存占用会稍大。。。）

**Comment by smallevil** [comment]
OK,谢了.
我试试改一下图片选择工具吧.

**Comment by huhuanming** [comment]
好的，祝好运！
如果还有问题的话，可以在下面留言或者开新的 issue。

三天内没有新问题的话，我就把这个 session 关闭掉。

**Comment by smallevil** [comment]
好的.多谢

**Comment by smallevil** [comment]
在QiniuFile这个类里,如果是图片,则有这么一条语句

self.mimeType = @"image/jpeg";

那么,如果是PNG文件呢???
会不会出现我说的问题?

**Comment by huhuanming** [comment]
这个还好。。服务器不会依靠这个为判断依据。
如果你担心的话，可以判断下。。

😳 但实际上这个属性，是可以不传的。。。

**Comment by smallevil** [comment]
我注释掉,试了半天,确实没什么影响.

**Comment by huhuanming** [comment]
所以我感觉 Bug 点还是在于相册照片存在 iCloud，然后本地没有的问题上。。。

**Comment by zhenghongchuan** [comment]
因为iCloud，用来用去我还是在用系统自带的相册调用了，懒得折腾

**Comment by huhuanming** [comment]
😳

**Comment by smallevil** [comment]
@zhenghongchuan 
没看懂.
我现在用的是TZImagePickerController
https://github.com/banchichen/TZImagePickerController

**Comment by zhenghongchuan** [comment]
@smallevil 
没用过这个三方组件，iCloud相片测试过吗？

**Comment by smallevil** [comment]
我从来不用这东西,而且,也没法短时间内搞几十G照片存进去.
:(

我看在POSAdjustedAssetReaderIOS8.m文件的第96行,有一句这个
options.networkAccessAllowed = NO;
这个网上有说是控制是否从icloud下载照片的.
但我OC开发是半吊子,你们看看和这个是不是有什么影响??

**Comment by huhuanming** [comment]
只能 try 了。。0  -    0 打开试试？

**Comment by zhenghongchuan** [comment]
这个东西用的人可太多了，很重要。

**Comment by huhuanming** [comment]
0  -  0 我抽空研究下。。。这个。。POSAdjustedAssetReaderIOS8 是从一个数据流的库里面引过来的。。

**Comment by zhenghongchuan** [comment]
其实这个不用我们做啊，系统自带相册的逻辑是你点选了这个图之后，他马上去下这个图的原图数据，然后给你的Asset和本地的没差别了，主要任务在于相册组件怎么做

**Comment by huhuanming** [comment]
有理。。。系统大法好。。。

**Comment by smallevil** [comment]
@zhenghongchuan
按理来说应该是这样的.
只是现在用户反馈上传偶尔会出现这个问题.
我这边又死活测不出来.
只能靠猜了.
最怕这种不能复现的BUG.

**Comment by huhuanming** [comment]
拿不到 file 的时候加个提醒。。让用户重选下？

**Comment by zhenghongchuan** [comment]
@smallevil 
我这边做一般直接用asset进行处理，判断他original什么什么的，不知道你一半是怎么做的

**Comment by huhuanming** [comment]
今天在微信里面选了下 iCloud 的图片。。。发现这个处理其实还真的还有点麻烦。。
可以自己试一下

**Comment by zhenghongchuan** [comment]
所以说啊，系统大法好。

**Comment by zhenghongchuan** [comment]
而且，系统的相册跟系统相机走的是同一个delegate，舒服
