### ISSUE TITLE
你好,我有检测到你的库里面有内存泄露点

### ISSUE THREAD

**Issue by liushuangddu** [huhuanming/qiniu_upload#27]
- (void)addFile:(QiniuFile *)file
{
    [self.files addObject:file];
}
addObject 有一个字节的泄露
------------------------------
startUpload 这个方法:
NSURLSession 创建过程中有11个字节的泄露,这个系统的类,我也不知道该怎么办.NSOperation 的 block 里面也有4个字节的内存泄露
----------------------------
uploadToken 这个方法
return 语句的字符串生成方法有1个字节的内存泄露
--------------------------
initWithToken 这个方法
两个 alloc 均有一个字节的内存泄露
目前就发现这么多,,,,
望: 尽快修复,,
PS: 你的库写的不错>--<

**Comment by huhuanming** [comment]
最新的代码里面没有  NSOperation 了。。

然后 NSURLSession 的内存泄露原因可以 Google 一下 nsurlsession memory leak。

暂时没有找到什么比较好的解决方案，按苹果官方的解释是，不要去重复创建 NSURLSession， 尽量做成单例，这样就会减少泄露的发生概率。

根据我最新的代码测试，大约五五开会泄露。。

0  - 0 也是非常的头疼。
