### ISSUE TITLE
我更新了之后,突然不能上传了>...<

### ISSUE THREAD

**Issue by liushuangddu** [huhuanming/qiniu_upload#28]
- (void)addFile:(QiniuFile *)file
{
    [self.files addObject:file];
}
addObject 有一个字节的泄露
------------------------------
startUpload 这个方法:
NSURLSession 创建过程中有11个字节的泄露,这个系统的类,我也不知道该怎么办.NSOperation 的 block 里面也有4个字节的内存泄露
----------------------------
uploadToken 这个方法
return 语句的字符串生成方法有1个字节的内存泄露
--------------------------
initWithToken 这个方法
两个 alloc 均有一个字节的内存泄露
目前就发现这么多,,,,
望: 尽快修复,,
PS: 你的库写的不错>--<

**Comment by liushuangddu** [comment]
几个 handler 不走,但是上传完成的 handler 会走

**Comment by huhuanming** [comment]
0  -   0 咋回事呢。。

**Comment by huhuanming** [comment]
那几个 handler 不走呢。。

**Comment by huhuanming** [comment]
测了下。。。都走啊。。。
