### ISSUE TITLE
 上传服务器会报400错误

### ISSUE THREAD

**Issue by chenfengfeng** [huhuanming/qiniu_upload#29]

**Comment by chenfengfeng** [comment]
error: Error Domain=https://upload.qbox.me Code=400 "{"error":"incorrect region, please use up-z2.qiniu.com"}" UserInfo={NSLocalizedDescription={"error":"incorrect region, please use up-z2.qiniu.com"}}

**Comment by huhuanming** [comment]
晚上会增加一个设置，可以配置 domain。

如果比较急的话，可以修改  Classes/QiniuUploader.m  里的域名

```
#define kQiniuUploadURL @"https://upload.qbox.me"
```

**Comment by chenfengfeng** [comment]
已经改啦~

**Comment by huhuanming** [comment]
0  - 0现在大家 close 好快。。。

**Comment by chenfengfeng** [comment]
😂问题解决了当然 close 啦

**Comment by huhuanming** [comment]
那我还是晚上更新一波。。。加个 api 的事。。

0  -  0下周应该就可以开始撸 swift 版了

`Pure Swift, No Dependency`
