### ISSUE TITLE
怎样获取刚上传文件的url？

### ISSUE THREAD

**Issue by bagusflyer** [huhuanming/qiniu_upload#3]
你好，现在progress正常工作，上传也很好。不过还是不明白怎样获取刚上传那个文件的url。代码如下：

    uploader.uploadOneFileSucceeded = {(operation : AFHTTPRequestOperation!, index : NSInteger, key : String?) in

从什么地方获取下载地址呢（指外链地址）？谢谢

还一个问题就是，好像无法指定上传文件的文件名了吧？比如我的文件是“file.mp3”，但上传后的文件是类似这种“Gq-L37WmgldZtqdsc_BVVPf9G-Lc”.

**Comment by huhuanming** [comment]
你这个咋打不开呢。。。=  =像下面这样就可以打开了
http://7sbqrd.com2.z0.glb.clouddn.com/01b6961907c68ea8901137b0a881e27f

七牛有两个cdn地址
7sbqrd.com2.z0.glb.qiniucdn.com 
7sbqrd.com2.z0.glb.clouddn.com

来来来。。。看看我上传的歌曲
http://7sbqrd.com2.z0.glb.clouddn.com/loDyXEyyLF1T0Ocgo-X7AoA4mG3O

**Comment by bagusflyer** [comment]
cdn地址是固定的吗？我可以随意使用一个？

**Comment by huhuanming** [comment]
是固定的。。。所以只要知道key 就好了。。=  皿 = 完全大丈夫

**Comment by huhuanming** [comment]
我看到你再其他地方求用 SBJson 啊。。。=  =听君一席话。JsonModel 好用得多。。

**Comment by bagusflyer** [comment]
那就是说我所有的上传都在：http://7xiopt.com1.z0.glb.clouddn.com ?

还有你上传的url可以直接在浏览器中播放，而我的会导致下载。我估计你上传时设置了正确的content type。

**Comment by huhuanming** [comment]
我开启了七牛的云端检测文件类型滴。。。=  皿= 你这是mp3？

**Comment by huhuanming** [comment]
有可能云端没查出来。。你再换个mp3试试诶？
不过也不影响吧。。

**Comment by huhuanming** [comment]
开启云端检查的代码 我写死在 QinniuUploader 里面滴。

**Comment by bagusflyer** [comment]
我的检测为：application/octet-stream

**Comment by huhuanming** [comment]
=  皿 = 我开放下写mime的接口？
不过这个不影响你使用流媒体播放七牛的东西。。。

**Comment by bagusflyer** [comment]
谢谢

**Comment by huhuanming** [comment]
不客气啦。。

**Comment by bagusflyer** [comment]
还是需要你开放下mimetype的接口，否则在封面点击可以播放，但点击进入后显示空白，我估计是因为mimetype不对。谢谢

**Comment by huhuanming** [comment]
你好。。我会马上追加的。= w =最多今晚。。

**Comment by bagusflyer** [comment]
我发现我设置QiniuFile中的mimeType为“audio/mpeg”，但结果不起作用，最后还是变成application/octet-stream，不知何故，另外上传时不知是否能自己确定上传后的文件名，包括后缀比如（myfile.mp3）之类的。谢谢，不急！

**Comment by huhuanming** [comment]
是这样的。。你是要音频流媒体还是视频流媒体呢
如果是视频的话 只支持 mp4 加 aac 
音频mp3格式也有特定要求哦

**Comment by bagusflyer** [comment]
我目前是mp3，分享后点击封面上的播放按钮可以播放，但进入后就显示空白页面。我估计应该是mimetype不对，微信没有自动检测。在qiniu中显示为application/octet-stream，但以前自己上传为audio/mpeg的就没问题。

**Comment by huhuanming** [comment]
感觉是mimetype没找到合适的

**Comment by bagusflyer** [comment]
七牛可以指定上传后的文件名吗？

**Comment by huhuanming** [comment]
可以的 设置key就好了

**Comment by bagusflyer** [comment]
QiniuToken.registerWithScope("x83-84", secretKey: "-83BvAJoT2ELb3gREy7_zdtfdfPkzrslB5ojTsJUQ", accesskey: "8HYacpFdcm-DoVaZBZmqE4oejEB9dpcgs7U6_mNy")
        
        let data = NSData(contentsOfFile: self.path)
        let file = QiniuFile(fileData: data)

        file.mimeType = "audio/mpeg"

我是这样做的，请问怎样指定文件名？谢谢

**Comment by huhuanming** [comment]
对不起。T A T接口暂时没给出。。因为我以为没啥用。。

**Comment by bagusflyer** [comment]
我指定key为xxxx.mp3，然后file.mimeType = "audio/mpeg"，在QiniuUploader.m中设置断点运行：

 [formData appendPartWithFileData:theFile.rawData name:@"file" fileName:@"file" mimeType:theFile.mimeType];

此时的mimetype正确，当上传后还是application/octet-stream，导致播放不正常，不知何故？
