### ISSUE TITLE
如果是PHAsset应该如何处理呢?

### ISSUE THREAD

**Issue by chenfengfeng** [huhuanming/qiniu_upload#30]
我看了下你的 file 只支持之前的ALAsset,那么PHAsset的处理呢?建议可以加多一个上去

**Comment by huhuanming** [comment]
现在没处理这个，0  -  0 可以拿到 nsdata 然后上传（比较费资源）

准备开撸 swift 版。。。就支持 PHAsset  不支持 ALAsset 了。。打算面向协议撸。。
这个估计只修 bug 咯

**Comment by chenfengfeng** [comment]
我看了下, PHAsset要拿到 data 的话需要通过一个PHImageManager类的 block 来拿到,但是这样的就导致 block 会后面走,files 会变成空...

**Comment by huhuanming** [comment]
那你需要考虑下异步操作了。。

如果是 swift 的话，可以尝试用下 promise。。
