### ISSUE TITLE
如果没有文件要上传调用上传的方法就会报错

### ISSUE THREAD

**Issue by hongdong** [huhuanming/qiniu_upload#5]
如果没有文件要上传调用上传的方法就会报错

**Comment by huhuanming** [comment]
没太懂诶。。能否详细解释下呢

**Comment by wendellwyh** [comment]
- (Boolean)startUpload
{
    if (!self.files) {

把判断改为下面应该就可了
- (Boolean)startUpload
{
    if (!self.files || self.files.count <= 0) {

**Comment by huhuanming** [comment]
能提个 pr 就好了 :-D
