### ISSUE TITLE
文件名称无法保留，需要保留原来的名称

### ISSUE THREAD

**Issue by wendellwyh** [huhuanming/qiniu_upload#6]

**Comment by huhuanming** [comment]
我周末更新下。。3q

**Comment by wendellwyh** [comment]
抱歉，可以保留原来文件名称的，使用withKey: fileName即可。
是否有什么问题就不知道了，没有中文的文件名目前来看可以。
谢谢！

**Comment by wendellwyh** [comment]
只是一种讨巧的办法，建议新开一个接口，withName:(NSString *)fileName
