### ISSUE TITLE
读取程序目录下NSURL失败

### ISSUE THREAD

**Issue by wendellwyh** [huhuanming/qiniu_upload#7]
sample：
// fileName = /var/mobile/Containers/Data/Application/03521F90-5F3D-4F22-AC18-53F130AFAA5E/Library/Caches/C6BFF8CD64F842C3878D9452A15CA789_20160107134914_001.mp4
qiniuFile = [[QiniuFile alloc] initWithAssetURL: [NSURL fileURLWithPath:fileName]];
 [_uploader addFile:qiniuFile];

上传时会报无法加载图片，源码默认从assert里面加载，建议兼容自定义的文件名称路径。
而批量的使用initWithFileData会大量占用内容。

**Comment by huhuanming** [comment]
非常抱歉。。最近才开始处理 issue 好的，我会注意修改这个问题的非常感谢
