### ISSUE TITLE
[uploader cancelAllUploadTask] 取消不了任务

### ISSUE THREAD

**Issue by UriChan** [huhuanming/qiniu_upload#9]
如题

**Comment by huhuanming** [comment]
收到啦。。T  A T 我确认一下哈。。这位亲，感谢你的反馈。。有兴趣可以提提 pr 噢

**Comment by huhuanming** [comment]
0 -  0 是我之前升级了 AFNetworking 我的问题，我现在开始修复哈，等会儿就发到 CocoaPods 里面

**Comment by huhuanming** [comment]
我在 1.5.4 中修复了这个问题，你可以更新下载尝试。

-  w  -不过还有些问题，内存占用上的问题，我会在周末更新一个比较大的更新，移除 AFNetworking，然后减小内存占用，希望继续支持，谢谢使用
